### ISSUE TITLE
Correção dos Richpictures com foco no usuário leitor

### ISSUE THREAD

**Issue by williamelias** [williamelias/Req-01-2019-medium#1]
- [x] Definir foco central no _richpicture_
- [x] Definir semântica adequada conforme o fluxo
- [x] Padronizar linguagem para PT-BR, facilitando a criação ulterior do lexo
- [x] Definição dos stakeholders
- [x] Inserir as fontes dos dados obtidos

**Comment by gabrielfilipe7unb** [comment]
Como seria "Inserir fontes dos dados obtidos"?

**Comment by williamelias** [comment]
@gabrielfilipe7unb , por as referências dos dados expostos por meio do richpicture criado.
