### ISSUE TITLE
Pesquisa a respeito do Questionário

### ISSUE THREAD

**Issue by williamelias** [williamelias/Req-01-2019-medium#17]
Deverá se pesquisar como poderá se aplicar o questionário em face a aplicação escolhida.
Respondendo as seguintes perguntas:

- [x] Qual o foco da pesquisa

- [x] Quais as possíveis ramificações de acordo com as respostas binárias

- [x] Qual o formato adequado para se fazer a construção do questionário

**Comment by williamelias** [comment]
pode-se adicionar outros critérios de aceitação

**Comment by gabrielfilipe7unb** [comment]
Pode fechar essa issue?

**Comment by gabrielfilipe7unb** [comment]
@gabrielfilipe7unb Fechei
