### ISSUE TITLE
Inserir modelos de richpicture na wiki

### ISSUE THREAD

**Issue by williamelias** [williamelias/Req-01-2019-medium#5]
Inserir os  modelos de richpicture na página destinada a exposição dos modelos criados pelo grupo durante a dinâmica e reuniões.

- [x] Inserir modelos com foco no usuário
- [x]  Inserir modelos com foco no escritor
- [x] Inserir rascunhos e modelos digitais

**Comment by MatheusBlanco** [comment]
Inseridos os meus
